// Angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog, MatDialogRef} from '@angular/material/dialog';
import { LoginComponent } from '../login/login.component';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(private dialog: MatDialog) { }

  ngOnInit(): void {
  }

  openLoginForm(){
    this.dialog.open(LoginComponent, {width:'500px', height:'450px'});
  }

}

<mat-toolbar color="primary">
    <span><img src="/assets/images/logo.png" height=30 width=41></span>
    <a mat-button routerLink="/home" routerLinkActive="active"><span class="fa fa-home fa-lg"></span> Home</a>
    <a mat-button routerLink="/about" routerLinkActive="active"><span class="fa fa-info fa-lg"></span> About</a>
    <a mat-button routerLink="/menu" routerLinkActive="active"><span class="fa fa-list fa-lg"></span> Menu</a>
    <a mat-button routerLink="/contact" routerLinkActive="active"><span class="fa fa-address-card fa-lg"></span> Contact</a>
    <span class="flex-spacer"></span>
    <a mat-button (click)="openLoginForm()"> <span class="fa fa-sign-in fa-lg" >  Login </span></a>
  </mat-toolbar>
  
  <div class="container jumbotron"
      fxLayout="row"
      fxLayout.sm="column" 
      fxLayout.xs="column" 
      fxLayoutAlign.xs="start center"
      fxLayoutAlign.sm="start center" 
      fxLayoutAlign.gt-sm="center center" 
      fxLayoutGap="10px">
  
    <div fxFlex fxFlex.gt-sm="50%">
      <h1>Ristorante Con Fusion</h1>
      <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our lipsmacking creations
        will tickle your culinary senses!</p>
    </div>
    <div fxFlex fxFlex.gt-sm="20%">
      <img src="/assets/images/logo.png" alt="Logo">
    </div>
    <div fxFlex></div>
  </div>

// React/confusion/src/components/HeaderComponent.js
import { Navbar, NavbarBrand, Jumbotron } from "reactstrap";

const Header = () => {
  return (
    <>
      <Navbar dark>
        <div className="container">
          <NavbarBrand href="/">Ristorante Con Fusion</NavbarBrand>
        </div>
      </Navbar>
      <Jumbotron>
        <div className="container">
          <div className="row row-header">
            <div className="col-12 col-sm-6">
              <h1>Ristorante Con Fusion</h1>
              <p>
                We take inspiration from the world's best cuisines, and create a
                unique fusion experience. Our lipsmacking creation will tickle
                your culinary senses !!
              </p>
            </div>
          </div>
        </div>
      </Jumbotron>
    </>
  );
};

export default Header;
